[package]
name = "nzcvm"
version = "0.1.0"
edition = "2024"

[lib]
name = "nzcvm"
crate-type = ["cdylib", "rlib"]

[features]
high_precision = []

[dependencies]
approx = "0.5.1"
bitfield-struct = "0.13.0"
bvh = { version = "0.12.0" }
deepsize = "0.2.0"
enum_dispatch = "0.3.13"
memmap2 = "0.9"
nalgebra = "0.34.0"
ndarray = { version = "0.17.2", features = ["approx", "rayon"] }
numpy = "0.29.0"
pyo3 = { version = "0.29.0", features = ["serde"] }
pythonize = "0.29.0"
rayon = "1.12.0"
serde = { version = "1.0.229", features = ["derive"] }
small-collections = "0.6.0"
smallvec = "1.15.2"
zerocopy = { version = "0.8", features = ["derive"] }


[dev-dependencies]
approx = "0.5.1"
proptest = "1"
tempfile = "3"
criterion = { version = "=0.5.1", features = ["html_reports"] }
pprof = { version = "0.15.0", features = ["flamegraph", "criterion"] }


[[bench]]
name = "model_bench"
harness = false

[profile.release]
lto = "thin"
codegen-units = 1
