"""Global object registry for dask-safe handling of unpicklable Rust-backed objects.

With the dask ``distributed`` scheduler running ``processes=False`` (thread
workers only), all workers share the same Python process.  This module exposes:

* :data:`REGISTRY` -- a global ``{uuid → object}`` dictionary.  Every key is a
  UUID string minted at serialisation time.

* :func:`register_dask_type` -- registers custom ``dask_serialize`` /
  ``dask_deserialize`` handlers for a type.  When distributed encounters an
  object of the registered type as a task argument it calls ``dask_serialize``,
  which stores the object in :data:`REGISTRY` under a fresh UUID and returns
  only the UUID.  ``dask_deserialize`` retrieves the object by UUID from the
  same registry.  Because ``processes=False`` keeps every worker in the same
  process, the lookup always succeeds without copying data.

* :func:`pipeline_context` -- a :mod:`contextlib` context manager that clears
  :data:`REGISTRY` after the pipeline (including any lazy dask ``.compute()``
  calls) finishes, releasing all cached objects.

Pipeline layers must load their resources (models, surfaces, …) *outside* any
``map_blocks`` / ``apply_ufunc`` boundary, then pass the loaded objects as
explicit kwargs so that dask can serialise them via the registered handlers.
"""

import contextlib
import logging
import uuid
from typing import Any

logger = logging.getLogger(__name__)

#: Global pool mapping UUID strings to Python objects.
#:
#: Keys are UUID strings generated by :func:`register_dask_type`'s serialize
#: handler.  :func:`pipeline_context` empties the pool as it exits.
REGISTRY: dict[str, Any] = {}


def pickle_pass(obj: Any) -> str:
    obj_id = uuid.uuid4().hex
    REGISTRY[obj_id] = obj
    return obj_id


@contextlib.contextmanager
def pipeline_context():
    """Context manager that clears the object registry after the pipeline finishes.

    Wrap the pipeline execution *including any lazy* ``.compute()`` *calls*
    with this context, so that leaving the block releases every object
    :data:`REGISTRY` still caches.

    Examples
    --------
    >>> with pipeline_context():  # doctest: +SKIP
    ...     vm_result = execute_model_pipeline(velocity_model, pipeline)
    ...     formats.write_velocity_model(vm_result, output)
    """
    try:
        yield
    finally:
        n = len(REGISTRY)
        REGISTRY.clear()
        logger.debug("Object registry cleared (%d entries removed).", n)
