"""Write the synthetic dataset out in the formats the toolkit reads.

Each command evaluates a field from :mod:`nzcvm.synthetic` and serialises it
the way the corresponding real data product is serialised, so the synthetic
files flow through exactly the same readers, converters and layers as the
real ones.  ``just synthetic`` chains the whole lot together.

``dem`` and ``vs30`` write modeller-style HDF5: ``latitude``, ``longitude``
and a 2-D scalar. ``nzcvm surface convert`` then turns that into the Zarr
surface mesh that ``grid.surface`` and the Ely layer read.
"""

import gzip
from pathlib import Path
from typing import Annotated

import h5py
import numpy as np
import pyproj
import shapely
import shapely.ops
import typer

from nzcvm import synthetic
from nzcvm.coordinates import WGS84_EPSG
from nzcvm.scripts.convert_tomography import CRS_NZTM

app = typer.Typer(help="Generate a small synthetic dataset for local testing.")

#: Default surface sampling, about 750 m across the domain.
DEFAULT_SAMPLES = 64

TO_NZTM = pyproj.Transformer.from_crs(WGS84_EPSG, CRS_NZTM, always_xy=True)

Output = Annotated[Path, typer.Argument(help="Output path.", dir_okay=False)]
Samples = Annotated[int, typer.Option(help="Surface samples along each axis.", min=2)]


def write_surface(
    path: Path, lon: np.ndarray, lat: np.ndarray, values: np.ndarray, key: str
) -> None:
    """Write a modeller-style HDF5 surface.

    Parameters
    ----------
    path :
        Destination file.
    lon, lat :
        Ascending 1-D coordinate axes, in degrees.
    values :
        ``(len(lat), len(lon))`` array of surface values.
    key :
        Name of the scalar dataset, such as ``elevation`` or ``vs30``.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    with h5py.File(path, "w") as handle:
        handle.create_dataset("latitude", data=lat)
        handle.create_dataset("longitude", data=lon)
        handle.create_dataset(key, data=values)


def write_wgs84_polygon(path: Path, vertices: np.ndarray) -> shapely.Polygon:
    """Project *vertices* into NZTM and write them as gzipped WKB.

    The coastline layer measures distances in the projected CRS, so the
    polygon it reads needs the same projection.

    Parameters
    ----------
    path :
        Destination file.
    vertices :
        ``(N, 2)`` array of longitude, latitude vertices.

    Returns
    -------
    shapely.Polygon
        The projected polygon this wrote.
    """
    projected = shapely.ops.transform(TO_NZTM.transform, shapely.Polygon(vertices))
    path.parent.mkdir(parents=True, exist_ok=True)
    with gzip.open(path, "wb") as handle:
        handle.write(shapely.to_wkb(projected))
    return projected


def _surface_grid(
    samples: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    """Return the 1-D longitude and latitude axes plus their ``(lat, lon)`` mesh."""
    lon, lat = synthetic.DOMAIN.sample(samples, samples)
    mesh_lon, mesh_lat = np.meshgrid(lon, lat)
    return lon, lat, mesh_lon, mesh_lat


@app.command()
def dem(output: Output, samples: Samples = DEFAULT_SAMPLES) -> None:
    """Write the synthetic topography as an HDF5 surface."""
    lon, lat, mesh_lon, mesh_lat = _surface_grid(samples)
    write_surface(
        output, lon, lat, synthetic.elevation(mesh_lon, mesh_lat), "elevation"
    )


@app.command()
def vs30(output: Output, samples: Samples = DEFAULT_SAMPLES) -> None:
    """Write the synthetic Vs30 map as an HDF5 surface."""
    lon, lat, mesh_lon, mesh_lat = _surface_grid(samples)
    write_surface(output, lon, lat, synthetic.vs30(mesh_lon, mesh_lat), "vs30")


@app.command()
def coastline(output: Output) -> None:
    """Write the synthetic land polygon as gzipped WKB in NZTM."""
    write_wgs84_polygon(output, synthetic.land())


@app.command()
def profile(output: Output) -> None:
    """Write the synthetic 1-D velocity profile as an fd_modfile."""
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        handle.write(f"{len(synthetic.PROFILE)}\n")
        synthetic.PROFILE.to_string(handle, header=False, index=False)
        handle.write("\n")


@app.command()
def tomography(
    output: Output,
    n_horizontal: Annotated[
        int, typer.Option(help="Samples along each horizontal axis.", min=2)
    ] = 12,
    n_depth: Annotated[int, typer.Option(help="Samples through depth.", min=2)] = 10,
) -> None:
    """Write the synthetic tomography block in EP2020 CSV form."""
    frame = synthetic.tomography(n_horizontal=n_horizontal, n_depth=n_depth)
    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w") as handle:
        # The EP2020 reader skips a leading provenance line before the header.
        handle.write("Synthetic tomography model, generated by nzcvm synthetic\n")
        frame.to_string(handle, index=False)
        handle.write("\n")


@app.command()
def basin(
    name: Annotated[synthetic.BasinName, typer.Argument(help="Basin to write.")],
    directory: Annotated[
        Path, typer.Argument(help="Directory to write the basin inputs into.")
    ],
    samples: Samples = DEFAULT_SAMPLES,
) -> None:
    """Write one basin's outline and basement surface.

    ``nzcvm basin main`` turns these, plus the DEM, into a tetrahedral mesh.
    """
    model = synthetic.BASINS[name]
    directory.mkdir(parents=True, exist_ok=True)

    # construct_mesh reads the first geometry out of a collection.
    outline = shapely.GeometryCollection([shapely.Polygon(model.outline())])
    (directory / f"{name}_outline.geojson").write_text(shapely.to_geojson(outline))

    lon, lat, mesh_lon, mesh_lat = _surface_grid(samples)
    write_surface(
        directory / f"{name}_basement.h5",
        lon,
        lat,
        model.basement(mesh_lon, mesh_lat),
        "elevation",
    )


if __name__ == "__main__":
    app()
